export const combos = [
  {
    number: 11,
    title: "Green Chile",
    price: "$9.55",
    img: "green_chile_600x416.jpg",
    fontSize: 26,
  },
  {
    number: 12,
    title: "Adobada Plate",
    price: "$9.21",
    img: "adobada_plato_600x416.jpg",
    fontSize: 30,
  },
  {
    number: 13,
    title: "Chimichanga Plate",
    price: "$9.89",
    img: "chimichanga_plate_600x416.jpg",
    fontSize: 23,
  },
  {
    number: 14,
    title: "Two Carne Asada Burritos",
    price: "$14.14",
    img: "two_carne_asada_burritos_600x416.jpg",
    fontSize: 20,
  },
  {
    number: 15,
    title: "Carnitas Plate",
    price: "$9.89",
    img: "carnitas_plate_600x416.jpg",
    fontSize: 30,
  },
  {
    number: 16,
    title: "Two Fish Tacos",
    price: "$9.06",
    img: "two_fish_tacos_600x416.jpg",
    fontSize: 33,
  },
  {
    number: 17,
    title: "Chiles Relleno",
    price: "$9.55",
    img: "two_chiles_rellenos_600x416.jpg",
    fontSize: 28,
  },
  {
    number: 18,
    title: "Two Carne Asada Tacos",
    price: "$11.85",
    img: "two_carne_asada_tacos_600x416.jpg",
    fontSize: 23,
  },
  {
    number: 19,
    title: "Burrito & Enchilada",
    price: "$9.45",
    img: "burrito_and_enchilada_600x416.jpg",
    fontSize: 26,
  },
  {
    number: 20,
    title: "Taco & Enchilada",
    price: "$9.45",
    img: "taco_and_enchilada_600x416.jpg",
    fontSize: 28,
  },
]
