export const combos = [
  {
    number: 1,
    title: "Pollo Asada",
    price: "$9.55",
    img: "pollo_asado_600x416.jpg",
    fontSize: 2.8,
  },
  {
    number: 2,
    title: "Burrito & Taco",
    price: "$9.45",
    img: "burrito_and_taco_600x416.jpg",
    fontSize: 2.4,
  },
  {
    number: 3,
    title: "Two beef Tacos",
    price: "$9.45",
    img: "two_beef_tacos-600x416.jpg",
    fontSize: 2.4,
  },
  {
    number: 4,
    title: "Fajitas Chicken or Steak",
    price: "$11.85",
    img: "fajitas_chicken_or_steak_600x416.jpg",
    fontSize: 1.8,
  },
  {
    number: 5,
    title: "Two Enchiladas",
    price: "$8.76",
    img: "two_enchiladas_600x416.jpg",
    fontSize: 2.4,
  },
  {
    number: 6,
    title: "Camarones Rancheros",
    price: "$12.11",
    img: "camarones_rancheros_600x416.jpg",
    fontSize: 2,
  },
  {
    number: 7,
    title: "Tostada & Taco",
    price: "$9.45",
    img: "tostada_and_taco_600x416.jpg",
    fontSize: 2.4,
  },
  {
    number: 8,
    title: "4 Rolled Tacos With Guacamole",
    price: "$9.85",
    img: "4_rolled_tacos_with_guacomole_600x416.jpg",
    fontSize: 1.8,
  },
  {
    number: 9,
    title: "Carne Asada",
    price: "$12.31",
    img: "carne_asada_600x416.jpg",
    fontSize: 2.7,
  },
  {
    number: 10,
    title: "Two Chicken Tacos",
    price: "$9.45",
    img: "two_chicken_tacos_600x416.jpg",
    fontSize: 2.1,
  },
]
